'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    'sınıfı tarafından otomatik olarak oluşturuldu.
    'Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    'komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    '''<summary>
    '''  Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Aefnet_Login_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        '''  CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property aef_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aef-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property aefnetlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aefnetlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property alizeunion_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alizeunion-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property badge_default_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_default_min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property dc_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dc_min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property game_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property Home_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property info_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property Menu_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property off_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("off-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property profile_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("profile-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property ra2logo_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ra2logo-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property sovietunion_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sovietunion_min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property status_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property top5_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top5-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property top5logo_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top5logo-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Public ReadOnly Property welcome2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("welcome2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
